### ISSUE TITLE
Need help for completely different results

### ISSUE THREAD

**Issue by Finnhh** [baharefatemi/ReAlE#5]
Hi, Bahare Fatemi.

First of all, thanks for your contribution. I learned a lot of useful knowledge from your paper. 

However, when I used this code on github to experiment and found that the experimental results were very different. I don’t know if I missed any key content.

**Experimental parameters** are as follows:
-model RealE
-dataset FB-AUTO
-window_size 2
-ent_non_linearity sigmoid
-non_linearity sigmoid
-emb_dim 200
-lr 0.1
-num_iterations 1000
-batch_size 128
-nr 10
-input_drop 0.2
-hidden_drop 0.2

**The results** are as follows:
Raw setting:
	Hit@1  = 0.0
	Hit@3  = 0.09586641756188696
	Hit@10 = 0.27206912657636617
	MR  = 183.14187295656237
	MRR = 0.09598441618985529

Fil setting:
	Hit@1  = 0.07379729098552079
	Hit@3  = 0.12494161606725829
	Hit@10 = 0.3188930406352172
	MR  = 175.7971742176553
	MRR = 0.15123606072740794

**Comment by baharefatemi** [comment]
Thanks for your interest in our work. I haven't yet specified the hyperparameters for each dataset. Each dataset needs to be tuned to find the best hyperparameters. The hyperparameters you ran the code with do not necessarily correspond to the best ones. I will update the code with the best set of hyperparameters soon.

**Comment by Finnhh** [comment]
> Thanks for your interest in our work. I haven't yet specified the hyperparameters for each dataset. Each dataset needs to be tuned to find the best hyperparameters. The hyperparameters you ran the code with do not necessarily correspond to the best ones. I will update the code with the best set of hyperparameters soon.

Thanks for your reply.
