### ISSUE TITLE
About reproduing experiment results

### ISSUE THREAD

**Issue by kbs391kbs** [baharefatemi/ReAlE#6]
Hi Bahare,
I have read your papers of HypE and ReAlE, which are quite valuable to me, and thanks for your open source codes.

However, similar to Finnhh's issue in https://github.com/baharefatemi/ReAlE/issues/5,
I have also tried running the provided codes on JF17K with lr=0.2/0.08/0.1/0.05, emb_dim=200, hidden_dropout=input_dropout=0.0, nr=10, w=2, but the model achieves MRR of 0.23 after 400 epochs.

I am wondering if you could provide best hyper-parameters for ReAlE on JF17K, FB-AUTO and M-FB15K.
Besides, could you give some suggestions on hyper-parameter settings for ReAlE? I am quite curious why ReAlE is heavily affected by hyper-parameter setting (like from 0.2 to 0.5 on JF17K)

**Comment by kbs391kbs** [comment]
Thanks for your timely reply.
Unfortunately, I tried the provided hyper-parameters on JF17, which achieves MRR of 0.248 after 1000 epoch training. I am not sure if there is some details I missed. I may try this again after you provide more details about settings on all datasets.
Anyway, thanks for your reply. Hope you can provide details as soon as possible.
BTW, in paper the nr is said to be 10, which may be a typo (100 here).

**Comment by baharefatemi** [comment]
You may want to pull again as I have a new commit with a slight modification. I will provide the complete set of hyperparameters in about 10 days.
The nr is set to 10 for the results in the arxiv version of the paper. Furthur tuning (e.g., nr = 100) gives much better results. The setup I mentioned for JF17K gives better results compared to the results in the paper.

**Comment by kbs391kbs** [comment]
Thanks!
